# Port 2121 and port range 10090-10100 must be open

listen=NO
listen_port=2121
listen_ipv6=YES
pasv_enable=Yes
pasv_max_port=10100
pasv_min_port=10090

anonymous_enable=YES
local_enable=NO
write_enable=NO
anon_umask=0
anon_root=/var/ftp
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
log_ftp_protocol=YES
ftpd_banner=Welcome to BASTOS FTP service.
# secure_chroot_dir=/var/run/vsftpd/empty
# pam_service_name=vsftpd
ssl_enable=NO
hide_ids=YES
