test : test.c ../../token.h ../../token.c ../../bmemory.c ../../keywords.h ../../keywords.inc ../../ds_btree.c
	g++ -Wall -g -O0  -I ../.. -o test test.c ../../token.c ../../bmemory.c ../../ds_btree.c

clean:
	rm -f *.o
	rm -f test
