# ESP
CHIP = esp8266
BOARD = generic
FLASH_DEF = 1M64
ESPTOOL_PY = ../../Arduino/esptool/esptool.py
UPLOAD_PORT = /dev/ttyUSB0
ESP_ADDR = 192.168.0.22
TRACES_PORT = 8267

include ../makeEspArduino/makeEspArduino.mk

